version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: kb_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__TELEMETRY_ENABLED=false
    restart: unless-stopped

volumes:
  qdrant-data: 