version: '3'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT_ALLOW_CORS=true
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring

  mediawiki:
    image: mediawiki:1.40
    container_name: wiki_local
    ports:
      - "8080:80"
    volumes:
      - mediawiki-data:/var/www/html
    environment:
      - MEDIAWIKI_DB_HOST=database
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=wikipass
    depends_on:
      - database
    restart: unless-stopped
    
  database:
    image: mariadb:10.9
    container_name: wiki_db
    environment:
      - MARIADB_DATABASE=wikidb
      - MARIADB_USER=wikiuser
      - MARIADB_PASSWORD=wikipass
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    
  mysql:
    image: mysql:8.0
    container_name: grafana-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=grafana
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - grafana-net
    command: --default-authentication-plugin=mysql_native_password

  # 添加一个简单的示例应用，用于生成指标
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring

  mysql-exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: mysql-exporter
    ports:
      - "9102:9102"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - grafana-net
      - monitoring

networks:
  grafana-net:
    name: grafana-net
  monitoring:
    driver: bridge

volumes:
  qdrant-storage:
  grafana-storage:
  mediawiki-data:
  mariadb-data:
  mysql-storage:
  prometheus_data:
  grafana_data: