version: '3'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT_ALLOW_CORS=true
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_local
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mysql
    networks:
      - grafana-net

  mediawiki:
    image: mediawiki:1.40
    container_name: wiki_local
    ports:
      - "8080:80"
    volumes:
      - mediawiki-data:/var/www/html
    environment:
      - MEDIAWIKI_DB_HOST=database
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=wikipass
    depends_on:
      - database
    restart: unless-stopped
    
  database:
    image: mariadb:10.9
    container_name: wiki_db
    environment:
      - MARIADB_DATABASE=wikidb
      - MARIADB_USER=wikiuser
      - MARIADB_PASSWORD=wikipass
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    
  mysql:
    image: mysql:8.0
    container_name: grafana-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=grafana
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - grafana-net
    command: --default-authentication-plugin=mysql_native_password

networks:
  grafana-net:
    name: grafana-net

volumes:
  qdrant-storage:
  grafana-storage:
  mediawiki-data:
  mariadb-data:
  mysql-storage: