version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana_local
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    
  mediawiki:
    image: mediawiki:1.40
    container_name: wiki_local
    ports:
      - "8080:80"
    volumes:
      - mediawiki-data:/var/www/html
    environment:
      - MEDIAWIKI_DB_HOST=database
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=wikipass
    depends_on:
      - database
    restart: unless-stopped
    
  database:
    image: mariadb:10.9
    container_name: wiki_db
    environment:
      - MARIADB_DATABASE=wikidb
      - MARIADB_USER=wikiuser
      - MARIADB_PASSWORD=wikipass
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: kb_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./kb:/kb
    ports:
      - "9200:9200"
    restart: unless-stopped
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kb_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kb:/kb
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    
  qdrant:
    image: qdrant/qdrant
    container_name: kb_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    volumes:
      - qdrant-data:/qdrant/storage
      - ./qdrant_kb:/qdrant_kb
    environment:
      - QDRANT__SERVICE__TELEMETRY_ENABLED=false
    restart: unless-stopped

volumes:
  grafana-storage:
  mediawiki-data:
  mariadb-data:
  elasticsearch-data:
  qdrant-data: 