global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-vehicle-sales'
    scrape_interval: 30s
    static_configs:
      - targets: ['mysql-exporter:9102']

  # 如果需要监控更多服务，可以在这里添加更多的scrape_config 